import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 20,
  },
  stickyButtonContainer: {
    position: 'absolute', // 'absolute' instead of 'fixed' in React Native
    top: 0,
    backgroundColor: '#fff',
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  mt50: {
    marginTop: 50,
  },
  mt20: {
    marginTop: 20,
  },
  mb20: {
    marginBottom: 20,
  },
  mt10: {
    marginTop: 10,
  },
  headbackbtn: {
    transform: [{ translateX: -95 }],
  },
  backButton: {
    alignSelf: 'flex-start',
    width: 19,
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  logo: {
    width: '100%',
    maxWidth: 120,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#002366',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 18,
    color: '#000',
    marginBottom: 20,
    paddingLeft: 7,
    fontWeight: '600',
    lineHeight: 24,
    textAlign: 'left',
  },
  fontStyle: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 24,
    letterSpacing: 0.005,
    textAlign: 'left',
  },
  pb20: {
    paddingBottom: 20,
  },
  red: {
    color: 'red',
  },
  smallTextLogoOne: {
    width: 70,
    height: 20,
  },
  text: {
    fontSize: 16,
    color: '#666',
    marginBottom: 20,
  },
  flexRow: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  registerButton: {
    width: '80%',
    paddingVertical: 10,
    marginBottom: 10,
    backgroundColor: '#ff0000',
    color: '#fff',
    borderWidth: 0,
    borderRadius: 5,
    fontSize: 16,
    textAlign: 'center',
  },
  inputWrapper: {
    position: 'relative',
    width: '100%',
    maxWidth: 400,
  },
  iconInsideInput: {
    position: 'absolute',
    top: '50%',
    transform: [{ translateY: -50 }],
  },
  visibilityIcon: {
    right: 20,
    width: 20,
    height: 20,
  },
  inputField: {
    width: '100%',
    paddingVertical: 10,
    paddingLeft: 40,
    paddingRight: 40,
    outlineStyle: 'solid',
    outlineColor: 'rgba(226, 226, 226, 1)',
    borderColor: 'rgba(255, 255, 255, 1)',
    borderWidth: 1,
    backgroundColor: 'transparent',
    borderRadius: 5,
  },
  redLink: {
    color: '#ff0000',
    textDecorationLine: 'none',
  },
  underline: {
    textDecorationLine: 'underline',
  },
  bolder: {
    fontWeight: '700',
    fontSize: 14,
  },
  hrLine: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    width: '100%',
    marginVertical: 20,
  },
  orText: {
    position: 'relative',
    backgroundColor: '#fff',
    fontWeight: '600',
    fontSize: 12,
    paddingHorizontal: 10,
    zIndex: 1,
    whiteSpace: 'nowrap',
    marginBottom: 13,
  },
  hr: {
    position: 'absolute',
    width: '100%',
    borderTopWidth: 1,
    borderColor: '#ccc',
    margin: 0,
    top: '50%',
    zIndex: 0,
  },
  loginButtonLogin: {
    width: '80%',
    paddingVertical: 10,
    marginTop: 15,
    backgroundColor: '#fff',
    color: '#ff0000',
    borderColor: '#ff0000',
    borderWidth: 1,
    borderRadius: 5,
    fontSize: 16,
    textAlign: 'center',
  },
  verifyAccountContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    padding: 20,
  },
  verifyAccountHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
  },
  backIcon: {
    width: 24,
    height: 24,
  },
  verifyTitle: {
    fontSize: 18,
    marginTop: 40,
    fontWeight: '600',
    textAlign: 'left',
    width: '100%',
    paddingLeft: 10,
  },
  passMustContainChar: {
    marginTop: -13,
    marginLeft: -109,
  },
  errorMessage: {
    color: 'red',
    fontSize: 14,
    marginTop: -5,
    textAlign: 'left',
    width: '100%',
    paddingLeft: 4,
  },
  withdrawSection: {
    marginTop: 20,
    textAlign: 'center',
  },
  withdrawInstruction: {
    fontSize: 16,
    color: '#333',
    marginBottom: 10,
  },
  withdrawAmountBox: {
    fontSize: 24,
    fontWeight: 'bold',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 10,
    marginVertical: 10,
    backgroundColor: '#f8f9fa',
  },
  withdrawSlider: {
    width: '100%',
    marginVertical: 10,
  },
  sliderLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 14,
    color: '#777',
  },
  upiSection: {
    marginTop: 20,
  },
  upiTitle: {
    fontSize: 16,
    marginBottom: 5,
    textAlign: 'left',
  },
  upiInput: {
    width: '100%',
    padding: 10,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    marginBottom: 5,
  },
  upiInstruction: {
    fontSize: 14,
    color: '#777',
    textAlign: 'left',
  },
  safetyNote: {
    textAlign: 'center',
    fontSize: 14,
    color: 'green',
    marginTop: 10,
  },
  profileContainer: {
    width: '100%',
  },
  profileOptions: {
    flexDirection: 'column',
  },
  profileOption: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginVertical: 20,
    alignSelf: 'center',
  },
  profileName: {
    fontSize: 24,
    fontWeight: 'bold',
    marginVertical: 10,
  },
  profileEmail: {
    fontSize: 16,
    color: '#666',
    marginVertical: 5,
  },
  green: {
    color: 'rgba(0, 170, 99, 1)',
  },
  goBackButton: {
    width: '90%',
    maxWidth: 300,
    margin: 20,
    paddingVertical: 15,
    backgroundColor: 'red',
    color: 'white',
    borderRadius: 5,
    fontSize: 16,
    alignSelf: 'center',
  },
  referStatus: {
    marginVertical: 20,
    padding: 10,
    backgroundColor: '#eaf4ff',
    borderWidth: 1,
    borderColor: '#007bff',
    borderRadius: 5,
    fontSize: 16,
    color: '#333',
  },
  referCount: {
    color: 'red',
    fontWeight: 'bold',
  },
  referTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    marginVertical: 20,
  },
  referralImage: {
    width: '100%',
    maxWidth: 300,
    marginVertical: 20,
  },
  referSteps: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderWidth: 2,
    borderColor: 'rgba(60, 154, 251, 1)',
    borderRadius: 10,
    paddingVertical: 15,
    backgroundColor: '#fff',
  },
  step: {
    textAlign: 'center',
    flex: 1,
    fontSize: 14,
  },
  stepNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'rgba(1, 20, 123, 1)',
  },
  divider: {
    width: 2,
    height: 60,
    backgroundColor: 'rgba(60, 154, 251, 1)',
    marginHorizontal: 20,
  },
  referralCodeContainer: {
    marginVertical: 20,
  },
  referralCodeLabel: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 10,
    color: 'rgba(71, 85, 105, 1)',
  },
  referralCodeBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    backgroundColor: '#f9f9f9',
  },
  referralCode: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  copyButton: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    color: 'rgba(71, 85, 105, 1)',
    fontSize: 14,
    fontWeight: '500',
    borderRadius: 5,
  },
  socialInviteContainer: {
    marginVertical: 20,
  },
  socialInviteTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  socialIcons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  socialIcon: {
    width: 50,
    height: 50,
  },
  flexColCenter: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fadeColour: {
    color: 'rgba(100, 116, 139, 1)',
  },
});

export default styles;
